//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastVolumeFw.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlaySoundAfterVolumeChange {
            get {
                return ((bool)(this["PlaySoundAfterVolumeChange"]));
            }
            set {
                this["PlaySoundAfterVolumeChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnmuteWhileChangingVolume {
            get {
                return ((bool)(this["UnmuteWhileChangingVolume"]));
            }
            set {
                this["UnmuteWhileChangingVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAppDisabledInFullScreenMode {
            get {
                return ((bool)(this["IsAppDisabledInFullScreenMode"]));
            }
            set {
                this["IsAppDisabledInFullScreenMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VolumeControlWithMouseWheel {
            get {
                return ((bool)(this["VolumeControlWithMouseWheel"]));
            }
            set {
                this["VolumeControlWithMouseWheel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public uint WindowRightMargin {
            get {
                return ((uint)(this["WindowRightMargin"]));
            }
            set {
                this["WindowRightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint MouseWheelVolumeChangeStep {
            get {
                return ((uint)(this["MouseWheelVolumeChangeStep"]));
            }
            set {
                this["MouseWheelVolumeChangeStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPlaybackButtons {
            get {
                return ((bool)(this["ShowPlaybackButtons"]));
            }
            set {
                this["ShowPlaybackButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MiddleMouseButtonAction {
            get {
                return ((int)(this["MiddleMouseButtonAction"]));
            }
            set {
                this["MiddleMouseButtonAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string AppLanguage {
            get {
                return ((string)(this["AppLanguage"]));
            }
            set {
                this["AppLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> MixerApps {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["MixerApps"]));
            }
            set {
                this["MixerApps"] = value;
            }
        }
    }
}
