//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastVolumeFw.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastVolumeFw.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the app.
        /// </summary>
        public static string CloseTheApp {
            get {
                return ResourceManager.GetString("CloseTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit the program?.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experimental.
        /// </summary>
        public static string Experimental {
            get {
                return ResourceManager.GetString("Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the option is enabled and you are in full screen mode, the volume control will not be shown..
        /// </summary>
        public static string IsAppDisabledInFullScreenModeDescription {
            get {
                return ResourceManager.GetString("IsAppDisabledInFullScreenModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable in full screen mode.
        /// </summary>
        public static string IsAppDisabledInFullScreenModeLabel {
            get {
                return ResourceManager.GetString("IsAppDisabledInFullScreenModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have changed the language. The application will be restarted..
        /// </summary>
        public static string LanguageChangeMessage {
            get {
                return ResourceManager.GetString("LanguageChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language change.
        /// </summary>
        public static string LanguageChangeTitle {
            get {
                return ResourceManager.GetString("LanguageChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App language. Requires app restart..
        /// </summary>
        public static string LanguageLabelDescription {
            get {
                return ResourceManager.GetString("LanguageLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The action that occurs when the middle mouse button is pressed..
        /// </summary>
        public static string MiddleMouseButtonActionDescription {
            get {
                return ResourceManager.GetString("MiddleMouseButtonActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle mouse button action:.
        /// </summary>
        public static string MiddleMouseButtonActionLabel {
            get {
                return ResourceManager.GetString("MiddleMouseButtonActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of programs in the volume mixer.
        /// </summary>
        public static string MixerListLabel {
            get {
                return ResourceManager.GetString("MixerListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mute.
        /// </summary>
        public static string MmbaMute {
            get {
                return ResourceManager.GetString("MmbaMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string MmbaNone {
            get {
                return ResourceManager.GetString("MmbaNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open app settings.
        /// </summary>
        public static string MmbaOpenSettings {
            get {
                return ResourceManager.GetString("MmbaOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play or pause.
        /// </summary>
        public static string MmbaPlayPause {
            get {
                return ResourceManager.GetString("MmbaPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume change step when adjusting with the mouse wheel. Range: 1-10..
        /// </summary>
        public static string MouseWheelVolumeChangeStepDescription {
            get {
                return ResourceManager.GetString("MouseWheelVolumeChangeStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mouse wheel volume change step:.
        /// </summary>
        public static string MouseWheelVolumeChangeStepLabel {
            get {
                return ResourceManager.GetString("MouseWheelVolumeChangeStepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play standard system sound when you release the volume control..
        /// </summary>
        public static string PlaySoundAfterVolumeChangeDescription {
            get {
                return ResourceManager.GetString("PlaySoundAfterVolumeChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play sound when volume change completes.
        /// </summary>
        public static string PlaySoundAfterVolumeChangeLabel {
            get {
                return ResourceManager.GetString("PlaySoundAfterVolumeChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore defaults.
        /// </summary>
        public static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are about to restore default application settings..
        /// </summary>
        public static string RestoreDefaultsMessage {
            get {
                return ResourceManager.GetString("RestoreDefaultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore defaults.
        /// </summary>
        public static string RestoreDefaultsTitle {
            get {
                return ResourceManager.GetString("RestoreDefaultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display playback control buttons on the volume control window..
        /// </summary>
        public static string ShowPlaybackButtonsDescription {
            get {
                return ResourceManager.GetString("ShowPlaybackButtonsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show playback control buttons.
        /// </summary>
        public static string ShowPlaybackButtonsLabel {
            get {
                return ResourceManager.GetString("ShowPlaybackButtonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the parameter is enabled and the sound is muted, it will be unmuted when the sound level is changed..
        /// </summary>
        public static string UnmuteWhileChangingVolumeDescription {
            get {
                return ResourceManager.GetString("UnmuteWhileChangingVolumeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always unmute while changing volume.
        /// </summary>
        public static string UnmuteWhileChangingVolumeLabel {
            get {
                return ResourceManager.GetString("UnmuteWhileChangingVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unstable.
        /// </summary>
        public static string Unstable {
            get {
                return ResourceManager.GetString("Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The following options can lead to various errors.
        ///Use them at your own risk..
        /// </summary>
        public static string UnstableDescription {
            get {
                return ResourceManager.GetString("UnstableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When you move the mouse wheel within the application window, the volume changes..
        /// </summary>
        public static string VolumeControlWithMouseWheelDescription {
            get {
                return ResourceManager.GetString("VolumeControlWithMouseWheelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable volume control with the mouse wheel.
        /// </summary>
        public static string VolumeControlWithMouseWheelLabel {
            get {
                return ResourceManager.GetString("VolumeControlWithMouseWheelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offset of the main window from the right edge. Range: 0-100..
        /// </summary>
        public static string WindowRightMarginDescription {
            get {
                return ResourceManager.GetString("WindowRightMarginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Window right margin:.
        /// </summary>
        public static string WindowRightMarginLabel {
            get {
                return ResourceManager.GetString("WindowRightMarginLabel", resourceCulture);
            }
        }
    }
}
